backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "produits"
    label: "Produits"
    folder: "_produits"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre (slug)", name: "slug", widget: "string" }
      - { label: "Nom", name: "nom", widget: "string" }
      - { label: "Prix", name: "prix", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "markdown" }
      - { label: "Catégorie", name: "categorie", widget: "select", options: ["bijoux", "vetements"] }